##### DROP #####
DROP TABLE IF EXISTS UTGIFT;
DROP TABLE IF EXISTS KATEGORI_T;

##### CREATE #####
#KODEVERK
CREATE TABLE KATEGORI_T (
  KATEGORI_ID  INT(11)      NOT NULL AUTO_INCREMENT,
  NAVN         VARCHAR(55)  NOT NULL UNIQUE,
  OPPRETTET    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  OPPRETTET_AV VARCHAR(255) NOT NULL,
  PRIMARY KEY (KATEGORI_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

#DOMAIN
CREATE TABLE UTGIFT (
  UTGIFT_ID    INT(11)        NOT NULL AUTO_INCREMENT,
  MAANED       VARCHAR(55)    NOT NULL,
  KATEGORI_ID  INT(11)        NOT NULL,
  BELOP        DECIMAL(10, 0) NOT NULL,
  BESKRIVELSE  VARCHAR(1000),
  OPPRETTET    TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  OPPRETTET_AV VARCHAR(255)   NOT NULL,
  PRIMARY KEY (UTGIFT_ID),
  FOREIGN KEY (KATEGORI_ID) REFERENCES KATEGORI_T (KATEGORI_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

#POPULERING AV BASE
INSERT INTO KATEGORI_T (NAVN, OPPRETTET_AV) VALUES ("Mat", "Simen");
INSERT INTO KATEGORI_T (NAVN, OPPRETTET_AV) VALUES ("Felleskostnader", "Simen");
INSERT INTO KATEGORI_T (NAVN, OPPRETTET_AV) VALUES ("Huslån", "Simen");
INSERT INTO KATEGORI_T (NAVN, OPPRETTET_AV) VALUES ("Lånekassen", "Simen");
INSERT INTO KATEGORI_T (NAVN, OPPRETTET_AV) VALUES ("Ferie", "Simen");
