version: '3'

services:
  regnskap_db:
    image: mysql:latest
    container_name: regnskap_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassord
      MYSQL_USER: regnskap
      MYSQL_PASSWORD: regnskap_1234
      MYSQL_DATABASE: regnskap
    ports:
    - 33777:3306
    volumes:
      - ./mysql/db_setup/:/docker-entrypoint-initdb.d

  regnskap-core:
    container_name: regnskap_core
    depends_on:
      - regnskap_db
    links:
      - regnskap_db
    build:
      context: ./tomcat
    ports:
      - 8080:8080

  jenkins:
    container_name: jenkins_blueocean
    build:
      context: ./jenkins
    ports:
      - 8081:8080
    volumes:
       - ./jenkins/setup/jenkins_home:/var/jenkins_home
       - ./jenkins/setup/run/docker.sock:/var/run/docker.sock
       - ./jenkins/setup/home:/home